"""Case lookup against wiki/CASES_INDEX.yaml.

Returns case records that the Auditor can cite as similar-vertical examples
in audit artifacts. Filters by (game, industry, stage, vertical_id) and by
filter_mode (trust|exploratory|research) through source_provenance.

CASES_INDEX.yaml shape (generated by index-builder):
  cases:
    - case_id: case-amplitude
      slug: amplitude
      path: wiki/cases/amplitude.md
      company: Amplitude
      game: productivity
      industry: SaaS
      stage: scale
      nsm: { statement: "...", grain: "..." }
      inputs: [...]
      evolution: [...]
      outcome: still_active
      source: { ... }
      confidence_envelope: { tier, confidence, curator_status, ... }

Note: CASES_INDEX `industry` values are Title-Case framework-domain strings
(SaaS, QSR, fintech, B2B SaaS) — they do NOT match the kebab-lowercase
vertical_id industry slugs (b2b-saas, fintech, marketplace). So vertical_id
lookups go via verticals/_index.yaml's `representative_cases` list, NOT via
industry-string matching. Industry/game filters are still available but expect
the caller to use CASES_INDEX's own vocabulary.
"""

from __future__ import annotations

import copy
import logging
from functools import lru_cache
from pathlib import Path
from types import MappingProxyType
from typing import Optional

from helpers.file_helpers import safe_read_yaml
from helpers.north_star.source_provenance import FilterMode, filter_records

log = logging.getLogger(__name__)


class UnknownVerticalError(ValueError):
    """Raised when lookup() is given a vertical_id absent from verticals/_index.yaml.

    Falling back to game/industry filters in that case returns vertical-irrelevant
    cases while *looking* authoritative (audit finding R-3). Failing loudly forces
    the caller to either fix the vertical_id or omit it and filter explicitly.
    """


# ---------------------------------------------------------------------------
# mtime-keyed caches
# ---------------------------------------------------------------------------


@lru_cache(maxsize=8)
def _load_cases_cached(path_str: str, mtime_ns: int) -> tuple[dict, ...]:
    """Cached load of CASES_INDEX.yaml. Keyed on (path, mtime_ns)."""
    data = safe_read_yaml(path_str) or {}
    cases = data.get("cases") or []
    if not isinstance(cases, list):
        return ()
    return tuple(cases)


@lru_cache(maxsize=8)
def _load_verticals_cached(path_str: str, mtime_ns: int) -> dict:
    """Cached load of verticals/_index.yaml. Keyed on (path, mtime_ns)."""
    return safe_read_yaml(path_str) or {}


def _default_wiki_root() -> Path:
    return Path(__file__).resolve().parents[2] / ".claude" / "skills" / "north-star" / "wiki"


def _cases_path(wiki_root: Optional[Path | str]) -> Path:
    root = Path(wiki_root) if wiki_root else _default_wiki_root()
    return root / "CASES_INDEX.yaml"


def _verticals_index_path(wiki_root: Optional[Path | str]) -> Path:
    root = Path(wiki_root) if wiki_root else _default_wiki_root()
    return root / "verticals" / "_index.yaml"


def _load_cases(wiki_root: Optional[Path | str] = None) -> tuple[dict, ...]:
    path = _cases_path(wiki_root)
    if not path.is_file():
        return ()
    return _load_cases_cached(str(path), path.stat().st_mtime_ns)


def _resolve_vertical_to_cases(
    vertical_id: str,
    wiki_root: Optional[Path | str] = None,
) -> Optional[tuple[Optional[str], Optional[str], list[str]]]:
    """Look up a vertical_id in verticals/_index.yaml.

    Returns (industry_slug, game, representative_case_slugs) on hit, None if missing.

    Used by lookup() to derive (game) — and the authoritative case-slug list —
    from a vertical_id. Replaces the broken `_split_vertical_id` heuristic which
    failed on edge-case verticals like `edge-multi-game-hybrid` (game contains hyphens).
    """
    path = _verticals_index_path(wiki_root)
    if not path.is_file():
        return None
    data = _load_verticals_cached(str(path), path.stat().st_mtime_ns)
    for v in data.get("verticals", []):
        if isinstance(v, dict) and v.get("vertical_id") == vertical_id:
            return (
                v.get("industry"),
                v.get("game"),
                list(v.get("representative_cases") or []),
            )
    return None


def reload_cases() -> None:
    """Clear caches. Rarely needed — caches self-invalidate on mtime change."""
    _load_cases_cached.cache_clear()
    _load_verticals_cached.cache_clear()


# ---------------------------------------------------------------------------
# Public lookup API
# ---------------------------------------------------------------------------


def _freeze_case(case: dict) -> dict:
    """Return a deep-copied dict view of a case record so callers cannot
    mutate the cached entry through the returned reference. Used at every
    return path to enforce the "cache is read-only" invariant."""
    return copy.deepcopy(case)


def lookup(
    game: Optional[str] = None,
    industry: Optional[str] = None,
    stage: Optional[str] = None,
    vertical_id: Optional[str] = None,
    limit: int = 5,
    filter_mode: FilterMode = FilterMode.TRUST,
    wiki_root: Optional[Path | str] = None,
) -> list[dict]:
    """Look up case records matching the given filters.

    Resolution order when vertical_id is passed:
      1. Look up vertical_id in verticals/_index.yaml.
      2. Use the vertical's `representative_cases` list as the AUTHORITATIVE
         slug list — these are the curated examples for this vertical.
      3. Apply game/stage filters from the args ON TOP of those cases.
    If vertical_id is not passed: filter cases by game/industry/stage as given.

    Explicit `game` arg always wins over vertical-derived game.

    Args:
        game: filter on case.game (e.g., "productivity"). Case-insensitive.
        industry: filter on case.industry — uses CASES_INDEX's vocabulary
            (e.g., "SaaS", "fintech", "B2B SaaS"), NOT vertical_id slugs.
        stage: filter on case.stage (e.g., "scale", "growth", "early").
        vertical_id: convenience — derives game + uses representative_cases
            from verticals/_index.yaml.
        limit: max cases to return (default 5).
        filter_mode: trust|exploratory|research envelope gate.

    Returns: list of case dicts (deep-copied from cache for tamper-safety).
    """
    all_cases = _load_cases(wiki_root)

    # Guard: if NO filters were provided (no game, industry, stage, or vertical_id),
    # don't return the first N cases unfiltered — that produces vertical-irrelevant
    # results for any caller who expected a filtered lookup. Return [] explicitly so
    # the caller's "no cases" branch fires instead.
    if all(f is None for f in (vertical_id, game, industry, stage)):
        log.warning(
            "case_lookup called with no filters. Returning [] to avoid "
            "vertical-irrelevant results. Pass vertical_id, game, industry, "
            "or stage to filter, or use case_count() / get_by_slug() for "
            "different access patterns."
        )
        return []

    # If vertical_id was passed, pivot on representative_cases.
    candidate_slugs: Optional[set[str]] = None
    if vertical_id:
        resolved = _resolve_vertical_to_cases(vertical_id, wiki_root)
        if resolved is None:
            raise UnknownVerticalError(
                f"vertical_id={vertical_id!r} not found in verticals/_index.yaml. "
                f"Refusing to silently fall back to game/industry filters, which would "
                f"return vertical-irrelevant cases. Fix the vertical_id (run "
                f"vertical_classifier) or omit vertical_id and pass game/industry/stage "
                f"explicitly."
            )
        _, derived_game, rep_cases = resolved
        candidate_slugs = set(rep_cases) if rep_cases else set()
        # Explicit game arg wins; otherwise inherit derived game.
        if game is None and derived_game:
            game = derived_game

    # Apply field filters
    out = []
    for case in all_cases:
        if not isinstance(case, dict):
            continue
        if candidate_slugs is not None:
            slug = case.get("slug") or ""
            case_id = case.get("case_id") or ""
            if slug not in candidate_slugs and case_id not in candidate_slugs:
                continue
        if game and (case.get("game") or "").lower() != game.lower():
            continue
        if industry and (case.get("industry") or "").lower() != industry.lower():
            continue
        if stage and (case.get("stage") or "").lower() != stage.lower():
            continue
        out.append(case)

    # Apply envelope filter
    out = filter_records(out, mode=filter_mode)

    return [_freeze_case(c) for c in out[:limit]]


def get_by_slug(
    slug: str,
    wiki_root: Optional[Path | str] = None,
) -> Optional[dict]:
    """Look up a single case by slug (e.g., "amplitude"). Returns None if not found.

    Returns a deep-copied dict so callers can mutate without corrupting cache.
    Does NOT apply filter_mode — caller asked for this specific case by ID.
    """
    cases = _load_cases(wiki_root)
    for case in cases:
        if isinstance(case, dict) and case.get("slug") == slug:
            return _freeze_case(case)
    return None


def case_count(
    filter_mode: FilterMode = FilterMode.TRUST,
    wiki_root: Optional[Path | str] = None,
) -> int:
    """Return the count of cases passing filter_mode. Used for ship-gate signals."""
    cases = _load_cases(wiki_root)
    return len(filter_records(list(cases), mode=filter_mode))
